const languageTranslations = {
  en: [
    { value: 'ru', label: 'russian' },
    { value: 'en', label: 'english' },
    { value: 'fr', label: 'french' },
    { value: 'de', label: 'german' },
    { value: 'it', label: 'italian' },
    { value: 'es', label: 'spanish' },
    { value: 'zh', label: 'chinese' },
    { value: 'ja', label: 'japanese' },
    { value: 'hi', label: 'hindi' },
    { value: 'pt', label: 'portuguese' },
    { value: 'ar', label: 'arabic' },
    { value: 'ko', label: 'korean' },
    { value: 'tr', label: 'turkish' },
    { value: 'nl', label: 'dutch' },
    { value: 'sv', label: 'swedish' },
  ],
  ru: [
    { value: 'ru', label: 'русский (Россия)' },
    { value: 'us', label: 'английский (Соединенные Штаты)' },
    { value: 'fr', label: 'французский (Франция)' },
    { value: 'de', label: 'немецкий (Германия)' },
    { value: 'it', label: 'итальянский (Италия)' },
    { value: 'es', label: 'испанский (Испания)' },
    { value: 'zh', label: 'китайский (Китай)' },
    { value: 'ja', label: 'японский (Япония)' },
    { value: 'hi', label: 'индийский (Индия)' },
    { value: 'pt', label: 'португальский (Португалия)' },
    { value: 'ar', label: 'арабский (ОАЭ)' },
    { value: 'ko', label: 'корейский (Корея)' },
    { value: 'tr', label: 'турецкий (Турция)' },
    { value: 'nl', label: 'нидерланский (Нидерланды)' },
    { value: 'sv', label: 'шведский (Шведский)' },
  ],
  es: [
    { value: 'ru', label: 'Rusia' },
    { value: 'us', label: 'Estados Unidos' },
    { value: 'ca', label: 'Canadá' },
    { value: 'mx', label: 'México' },
    { value: 'gb', label: 'Reino Unido' },
    { value: 'de', label: 'Alemania' },
    { value: 'fr', label: 'Francia' },
    { value: 'it', label: 'Italia' },
    { value: 'es', label: 'España' },
    { value: 'cn', label: 'China' },
    { value: 'jp', label: 'Japón' },
    { value: 'in', label: 'India' },
    { value: 'br', label: 'Brasil' },
    { value: 'za', label: 'Sudáfrica' },
  ],
};

export const getLanguages = (language = 'ru') => {
  return languageTranslations[language] || languageTranslations['ru'];
};
