import { Footer } from "flowbite-react";
import { useTranslation } from "react-i18next";
import { SlSocialVkontakte } from "react-icons/sl";
import { BsDribbble, BsGithub, BsYoutube } from "react-icons/bs";
import { BiLogoFigma } from "react-icons/bi";

export default function TermsOfUse() {
   const { t } = useTranslation();

   return (
      <div className="p-12">
         <h1 className="text-4xl font-semibold">Input Studios – Terms of Use</h1> 
         <p className="mt-8 text-base">Last Updated: February 7, 2022</p>
         <h1 className="mt-8 text-3xl font-semibold">Acceptance of Terms</h1>
         <p className="mt-6 text-base">The services that Input Studios provides to you are subject to the following Terms of Use ("TOU"). Input Studios reserves the right to update and modify the TOU at any time without notice to you. The most current version of the TOU can be reviewed by clicking on the "Terms of Use" hypertext link located at the bottom of our Web pages. When we make updates to the TOU, Input Studios will update the date at the top of this page. By using the website after a new version of the TOU has been posted, you agree to the terms of such new version.</p>
         <h1 className="mt-8 text-3xl font-semibold">Description of Services</h1>
         <p className="mt-6 text-base">Through its network of Web properties, Input Studios provides you with access to a variety of resources, including developer tools, download areas, communication forums and product information (collectively "Services"). The Services, including any updates, enhancements, new features, and/or the addition of any new Web properties, are subject to these TOU.</p>
         <h1 className="mt-8 text-3xl font-semibold">Personal and Non-Commercial Use Limitation</h1>
         <p className="mt-6 text-base">Unless otherwise specified, the Services are for your personal and non-commercial use. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software, products or services obtained from the Services.</p>
         <h1 className="mt-8 text-3xl font-semibold">Privacy and Protection of Personal Information</h1>
         <p className="mt-8 text-base">See the <a href="https://inputstudios.ru/legal/intellectualproperty/infringement" className="text-blue-500 underline">Privacy Statement</a> disclosures relating to the collection and use of your personal data.</p>
         <h1 className="mt-8 text-3xl font-semibold">Content</h1>
         <p className="mt-8 text-base">All content included in or made available through the Services, such as text, graphics, logos, icons, images, sounds, music, digital downloads, data compilation, software, and documents is the exclusive property of Input Studios or its content suppliers and is protected by the various applicable trade dress, copyright, trademark, patent, and other intellectual property and unfair competition laws in the United States and internationally. All rights not expressly granted to you in this TOU are reserved and retained by Input Studios or its licensors, suppliers, publishers, rightsholders, or other content providers.</p>
         <h1 className="mt-8 text-3xl font-semibold">Software</h1>
         <p className="mt-8 text-base">Any software that is made available to download from the Services ("Software") is the copyrighted work of Input Studios and/or its suppliers. Use of the Software is governed by the terms of the end user license agreement, if any, which accompanies or is included with the Software ("License Agreement"). An end user will be unable to install any Software that is accompanied by or includes a License Agreement, unless he or she first agrees to the License Agreement terms. Third party scripts or code, linked to or referenced from this website, are licensed to you by the third parties that own such code, not by Input Studios.</p>
         <p className="mt-4 text-base">The Software is made available for download solely for use by end users according to the License Agreement. Any reproduction or redistribution of the Software not in accordance with the License Agreement is expressly prohibited by law, and may result in severe civil and criminal penalties. Violators will be prosecuted to the maximum extent possible.</p>
         <p className="mt-8 text-base font-bold">Without limiting the foregoing, copying or reproduction of the software to any other server or location for further reproduction or redistribution is expressly prohibited, unless such reproduction or redistribution is expressly permitted by the license agreement accompanying such software.</p>
         <p className="mt-8 text-base"><b>Restricted Rights Legend.</b> Any Software which is downloaded from the Services for or on behalf of the United States of America, its agencies and/or instrumentalities ("U.S. Government"), is provided with Restricted Rights. Use, duplication, or disclosure by the U.S. Government is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in Technical Data and Computer Software clause at DFARS 252.227-7013 or subparagraphs (c)(1) and (2) of the Commercial Computer Software - Restricted Rights at 48 CFR 52.227-19, as applicable. Manufacturer is Input Studios Corporation, One Input Studios Way, Redmond, WA 98052-6399.</p>
         <h1 className="mt-8 text-3xl font-semibold">Documents</h1>
         <p className="mt-8 text-base">Permission to use Documents (such as white papers, press releases, datasheets and FAQs) from the Services is granted, provided that (1) the below copyright notice appears in all copies and that both the copyright notice and this permission notice appear, (2) unless explicitly covered by another license or agreement, use of such Documents from the Services is for informational and non-commercial or personal use only and will not be copied or posted on any network computer or broadcast in any media, and (3) no modifications of any Documents are made. Accredited educational institutions, such as K-12, universities, private/public colleges, and state community colleges, may download and reproduce the Documents for distribution in the classroom. Distribution outside the classroom requires express written permission. Use for any other purpose is expressly prohibited by law, and may result in severe civil and criminal penalties. Violators will be prosecuted to the maximum extent possible.</p>
         <p className="mt-8 text-base">Documents specified above do not include the design or layout of the Input Studios.com website or any other Input Studios owned, operated, licensed or controlled site. Elements of Input Studios websites are protected by trade dress, trademark, unfair competition, and other laws and may not be copied or imitated in whole or in part. No logo, graphic, sound or image from any Input Studios website may be copied or retransmitted unless expressly permitted by Input Studios.</p>
         <h1 className="mt-8 text-3xl font-semibold">Representations and Warranties</h1>
         <p className="mt-8 text-base">Software is warranted, if at all, only according to the terms of the license agreement. <b>Except as warranted in the license agreement, Input Studios corporation hereby disclaims all warranties and conditions with regard to the software, including all warranties and conditions of merchantability, whether express, implied or statutory, fitness for a particular purpose, title and non-infringement.</b> For your convenience, Input Studios may make available as part of the services or in its software products, tools and utilities for use and/or download. <b>Input Studios does not make any assurances with regard to the accuracy of the results or output that derives from such use of any such tools and utilities.</b> Please respect the intellectual property rights of others when using the tools and utilities made available on the services or in Input Studios software products.</p>
         <p className="mt-8 text-base font-bold">Input Studios and/or its respective suppliers make no representations about the suitability of the information contained in the documents and related graphics published as part of the services for any purpose. all such documents and related graphics are provided "as is" without warranty of any kind. Input Studios and/or its respective suppliers hereby disclaim all warranties and conditions with regard to this information, including all warranties and conditions of merchantability, whether express, implied or statutory, fitness for a particular purpose, title and non-infringement. in no event shall Input Studios and/or its respective suppliers be liable for any special, indirect or consequential damages or any damages whatsoever resulting from loss of use, data or profits, whether in an action of contract, negligence or other tortious action, arising out of or in connection with the use or performance of information available from the services.</p>
         <p className="mt-8 text-base">The documents and related graphics published on the services could include technical inaccuracies or typographical errors. changes are periodically added to the information herein. Input Studios and/or its respective suppliers may make improvements and/or changes in the product(s) and/or the program(s) described herein at any time.</p>
         <h1 className="mt-8 text-3xl font-semibold">Limitation of Liability</h1>
         <p className="mt-8 text-base font-bold">In no event shall Input Studios and/or its respective suppliers be liable for any special, indirect or consequential damages or any damages whatsoever resulting from loss of use, data or profits, whether in an action of contract, negligence or other tortious action, arising out of or in connection with the use or performance of software, documents, provision of or failure to provide services, or information available from the services.</p>
         <h1 className="mt-8 text-3xl font-semibold">Member Account, Password, and Security</h1>
         <p className="mt-8 text-base">If any of the Services requires you to open an account, you must complete the registration process by providing us with current, complete and accurate information as prompted by the applicable registration form. You also will choose a password and a user name. You are entirely responsible for maintaining the confidentiality of your password and account. Furthermore, you are entirely responsible for any and all activities that occur under your account. You agree to notify Input Studios immediately of any unauthorized use of your account or any other breach of security. Input Studios will not be liable for any loss that you may incur as a result of someone else using your password or account, either with or without your knowledge. However, you could be held liable for losses incurred by Input Studios or another party due to someone else using your account or password. You may not use anyone else's account at any time, without the permission of the account holder.</p>
         <h1 className="mt-8 text-3xl font-semibold">No Unlawful or Prohibited Use</h1>
         <p className="mt-8 text-base">As a condition of your use of the Services, you will not use the Services for any purpose that is unlawful or prohibited by these terms, conditions, and notices. You may not use the Services in any manner that could damage, disable, overburden, or impair any Input Studios server, or the network(s) connected to any Input Studios server, or interfere with any other party's use and enjoyment of any Services. You may not attempt to gain unauthorized access to any Services, other accounts, computer systems or networks connected to any Input Studios server or to any of the Services, through hacking, password mining or any other means. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available through the Services. You may not attempt to copy or change, alter or otherwise  attempt to modify the Services or these TOU.</p>
         <h1 className="mt-8 text-3xl font-semibold">Use of Services</h1>
         <p className="mt-8 text-base">The Services may contain e-mail services, bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, photo albums, file cabinets and/or other message or communication facilities designed to enable you to communicate with others (each a "Communication Service" and collectively "Communication Services"). You agree to use the Communication Services only to post, send and receive messages and material that are proper and, when applicable, related to the particular Communication Service. By way of example, and not as a limitation, you agree that when using the Communication Services, you will not:</p>
         <ul className="ml-4 mt-4 list-disc list-outside pl-6 text-base">
            <li>Use the Communication Services in connection with surveys, contests, pyramid schemes, chain letters, junk email, spamming or any duplicative or unsolicited messages (commercial or otherwise).</li>
            <li className="mt-4">Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.</li>
            <li className="mt-4">Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, obscene, indecent or unlawful topic, name, material or information.</li>
            <li className="mt-4">Upload, or otherwise make available, files that contain images, photographs, software or other material protected by intellectual property laws, including, by way of example, and not as limitation, copyright or trademark laws (or by rights of privacy or publicity) unless you own or control the rights thereto or have received all necessary consent to do the same.</li>
            <li className="mt-4">Use any material or information, including images or photographs, which are made available through the Services in any manner that infringes any copyright, trademark, patent, trade secret, or other proprietary right of any party.</li>
            <li className="mt-4">Upload files that contain viruses, Trojan horses, worms, time bombs, cancelbots, corrupted files, or any other similar software or programs that may damage the operation of another's computer or property of another.</li>
            <li className="mt-4">Advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Services specifically allows such messages.</li>
            <li className="mt-4">Download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally reproduced, displayed, performed, and/or distributed in such manner.</li>
            <li className="mt-4">Falsify or delete any copyright management information, such as author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</li>
            <li className="mt-4">Restrict or inhibit any other user from using and enjoying the Communication Services.</li>
            <li className="mt-4">Violate any code of conduct or other guidelines which may be applicable for any particular Communication Service.</li>
            <li className="mt-4">Harvest or otherwise collect information about others, including e-mail addresses.</li>
            <li className="mt-4">Violate any applicable laws or regulations.</li>
            <li className="mt-4">Create a false identity for the purpose of misleading others.</li>
            <li className="mt-4">Use, download or otherwise copy, or provide (whether or not for a fee) to a person or entity any directory of users of the Services or other user or usage information or any portion thereof.</li>
         </ul>
         <p className="mt-6 text-base">Input Studios has no obligation to monitor the Communication Services. However, Input Studios reserves the right to review materials posted to the Communication Services and to remove any materials in its sole discretion. Input Studios reserves the right to terminate your access to any or all of the Communication Services at any time, without notice, for any reason whatsoever.</p>
         <p className="mt-6 text-base">Input Studios reserves the right at all times to disclose any information as Input Studios deems necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in Input Studios's sole discretion.</p>
         <p className="mt-6 text-base">Always use caution when giving out any personally identifiable information about yourself or your children in any Communication Services. Input Studios does not control or endorse the content, messages or information found in any Communication Services and, therefore, Input Studios specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Services. Managers and hosts are not authorized Input Studios spokespersons, and their views do not necessarily reflect those of Input Studios.</p>
         <p className="mt-6 text-base">Materials uploaded to the Communication Services may be subject to posted limitations on usage, reproduction and/or dissemination; you are responsible for adhering to such limitations if you download the materials.</p>
         <p className="mt-6 text-base font-bold">AI Services.</p>
         <p className="mt-6 text-base">”AI services” are services that are labeled or described by Input Studios as including, using, powered by, or being an Artificial Intelligence (“AI”) system.</p>
         <ul className="ml-4 mt-4 list-disc list-outside pl-6 text-base">
            <li><b>Reverse Engineering.</b> You may not use the AI services to discover any underlying components of the models, algorithms, and systems. For example, you may not try to determine and remove the weights of models.</li>
            <li className="mt-4"><b>Extracting Data.</b> You may not use web scraping, web harvesting, or web data extraction methods to extract data from the AI services.</li>
            <li className="mt-4"><b>Limits on use of data from the AI Services.</b> You may not use the AI services, or data from the AI services, to create, train, or improve (directly or indirectly) any other AI service. </li>
            <li className="mt-4"><b>Use of Your Content.</b> As part of providing the AI services, Input Studios will process and store your inputs to the service as well as output from the service, for purposes of monitoring for and preventing abusive or harmful uses or outputs of the service.</li>
            <li className="mt-4"><b>Third party claims.</b> You are solely responsible for responding to any third-party claims regarding your use of the AI services in compliance with applicable laws (including, but not limited to, copyright infringement or other claims relating to content output during your use of the AI services).</li>
         </ul>
         <h1 className="mt-8 text-3xl font-semibold">Materials Provided to Input Studios or Posted at any Input Studios Website</h1>
         <p className="mt-6 text-base">Input Studios does not claim ownership of the materials you provide to Input Studios (including feedback and suggestions) or post, upload, input or submit to any Services or its associated services for review by the general public, or by the members of any public or private community, (each a "Submission" and collectively "Submissions"). However, by posting, uploading, inputting, providing or submitting ("Posting") your Submission you are granting Input Studios, its affiliated companies and necessary sublicensees permission to use your Submission in connection with the operation of their Internet businesses (including, without limitation, all Input Studios Services), including, without limitation, the license rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Submission; to publish your name in connection with your Submission; and the right to sublicense such rights to any supplier of the Services.</p>
         <p className="mt-6 text-base">No compensation will be paid with respect to the use of your Submission, as provided herein. Input Studios is under no obligation to post or use any Submission you may provide and Input Studios may remove any Submission at any time in its sole discretion.</p>
         <p className="mt-6 text-base">By Posting a Submission you warrant and represent that you own or otherwise control all of the rights to your Submission as described in these Terms of Use including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the Submissions.</p>
         <p className="mt-6 text-base">In addition to the warranty and representation set forth above, by Posting a Submission that contain images, photographs, pictures or that are otherwise graphical in whole or in part ("Images"), you warrant and represent that (a) you are the copyright owner of such Images, or that the copyright owner of such Images has granted you permission to use such Images or any content and/or images contained in such Images consistent with the manner and purpose of your use and as otherwise permitted by these Terms of Use and the Services, (b) you have the rights necessary to grant the licenses and sublicenses described in these Terms of Use, and (c) that each person depicted in such Images, if any, has provided consent to the use of the Images as set forth in these Terms of Use, including, by way of example, and not as a limitation, the distribution, public display and reproduction of such Images. By Posting Images, you are granting (a) to all members of your private community (for each such Images available to members of such private community), and/or (b) to the general public (for each such Images available anywhere on the Services, other than a private community), permission to use your Images in connection with the use, as permitted by these Terms of Use, of any of the Services, (including, by way of example, and not as a limitation, making prints and gift items which include such Images), and including, without limitation, a non-exclusive, world-wide, royalty-free license to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Images without having your name attached to such Images, and the right to sublicense such rights to any supplier of the Services. The licenses granted in the preceding sentences for a Images will terminate at the time you completely remove such Images from the Services, provided that, such termination shall not affect any licenses granted in connection with such Images prior to the time you completely remove such Images. No compensation will be paid with respect to the use of your Images.</p>
         <h1 className="mt-8 text-3xl font-semibold">Notices and Procedure for Making Claims of Copyright Infringement</h1>
         <p className="mt-6 text-base">Pursuant to Title 17, United States Code, Section 512(c)(2), notifications of claimed copyright infringement should be sent to Service Provider's Designated Agent. All inquiries not relevant to the following procedure will not receive a response.</p>
         <p className="mt-6 text-base">See <a href="https://inputstudios.ru/legal/intellectualproperty/infringement" className="text-blue-500 underline">Notice and Procedure for Making Claims of Copyright Infringement.</a></p>
         <h1 className="mt-8 text-4xl font-semibold">Links to Third Party Sites</h1>
         <p className="mt-6 text-base">The links in this area will let you leave Input Studios's site. The linked sites are not under the control of <b>Input Studios and Input Studios is not responsible for the contents of any linked site or any link contained in a linked site, or any changes or updates to such sites. Input Studios is not responsible for webcasting or any other form of transmission received from any linked site.</b> Input Studios is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by Input Studios of the site.</p>
         <h1 className="mt-8 text-4xl font-semibold">Unsolicited Idea Submission Policy</h1> 
         <p className="mt-6 text-base">Input Studios or any of its employees do not accept or consider unsolicited ideas, including ideas for new advertising campaigns, new promotions, new products or technologies, processes, materials, marketing plans or new product names. please do not send any original creative artwork, samples, demos, or other works. the sole purpose of this policy is to avoid potential misunderstandings or disputes when Input Studios's products or marketing strategies might seem similar to ideas submitted to Input Studios. so, please do not send your unsolicited ideas to Input Studios or anyone at Input Studios. if, despite our request that you not send us your ideas and materials, you still send them, please understand that Input Studios makes no assurances that your ideas and materials will be treated as confidential or proprietary.</p>
         <div className="flex flex-wrap gap-4 mt-20">
            <p>{t("home_subscribe_news")}</p>
            <div className="flex flex-wrap gap-4">
               <Footer.Icon href="https://vk.com/inputstudios" target="_blank" icon={SlSocialVkontakte} />
               <Footer.Icon href="https://www.youtube.com/@input.studios" target="_blank" icon={BsYoutube} />
               <Footer.Icon href="https://www.figma.com/team_invite/redeem/IHhVbYADhWDiftybuzpjBl" target="_blank" icon={BiLogoFigma} />
               <Footer.Icon href="https://github.com/inputstudios" target="_blank" icon={BsGithub} />
               <Footer.Icon href="https://dribbble.com/inputstudios" target="_blank" icon={BsDribbble} />
            </div>
         </div>
      </div>
   );
}